name: CI workflow

# Event
on:
  push: 
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Job
jobs:
  # Job Name
  build:
  # runner
    runs-on: ubuntu-latest
    container: python:3.9-slim
    # Steps for Job:
    steps:
    # Checkout new branch
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: | # Pipe operator for multiple commands. Like So.
          python -m pip install --upgrade pip
          pip install -r requirements.txt
     
      - name: Lint with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests with nose
        run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app


